# Generated by Django 3.2.18 on 2023-04-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.TextField(max_length=255)),
                ('lastname', models.TextField(max_length=255)),
                ('username', models.TextField(unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.TextField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
